// <auto-generated />
using System;
using APIHavan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIHavan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("APIHavan.Data.Cliente", b =>
                {
                    b.Property<int>("clienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("clienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("APIHavan.Data.CondicaoPagamento", b =>
                {
                    b.Property<int>("condicaoPagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("dias")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("condicaoPagamentoId");

                    b.ToTable("CondicoesPagamentos");
                });

            modelBuilder.Entity("APIHavan.Data.HistoricoPreco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<double>("preco")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("HistoricoPrecos");
                });

            modelBuilder.Entity("APIHavan.Data.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("APIHavan.Data.RelatorioPagamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("HistorioPrecoid")
                        .HasColumnType("int");

                    b.Property<int?>("clienteId")
                        .HasColumnType("int");

                    b.Property<int?>("condicaoPagamentoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("HistorioPrecoid");

                    b.HasIndex("clienteId");

                    b.HasIndex("condicaoPagamentoId");

                    b.ToTable("RelatorioPagamentos");
                });

            modelBuilder.Entity("APIHavan.Data.HistoricoPreco", b =>
                {
                    b.HasOne("APIHavan.Data.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("APIHavan.Data.RelatorioPagamento", b =>
                {
                    b.HasOne("APIHavan.Data.HistoricoPreco", "HistorioPreco")
                        .WithMany()
                        .HasForeignKey("HistorioPrecoid");

                    b.HasOne("APIHavan.Data.Cliente", null)
                        .WithMany("RelatorioPagamento")
                        .HasForeignKey("clienteId");

                    b.HasOne("APIHavan.Data.CondicaoPagamento", "CondicaoPagamento")
                        .WithMany()
                        .HasForeignKey("condicaoPagamentoId");

                    b.Navigation("CondicaoPagamento");

                    b.Navigation("HistorioPreco");
                });

            modelBuilder.Entity("APIHavan.Data.Cliente", b =>
                {
                    b.Navigation("RelatorioPagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
